### ISSUE TITLE
Customiseable input action names

### ISSUE THREAD

**Issue by Flynsarmy** [krazyjakee/nodot#3]
We want to avoid clashing input action names. I suggest everywhere we have an input_action_pressed() we have an @export defining the action name. We can have defaults. For example here 
https://github.com/krazyjakee/nodot/blob/fe5be9d914b0ecdebe14ce20767987cec52c44b7/addons/nodot/characters/FirstPerson/FirstPersonCharacter.gd#L40 ) we could change it to
```gdscript
if event.is_action_pressed(escape_action): 
```
and at the top of the file:
```gdscript
@export var escape_action := "escape"
```

This would not only remove the hardcoded action name and potential clashes with existing actions, but have the added benefit of allowing developers to use different names on copies of the same component should they ever want to.

**Comment by Flynsarmy** [comment]
If you're happy with this idea I could send a PR

**Comment by krazyjakee** [comment]
Very happy with it. I'm working on the documentation generator so a PR would be great, thanks!
